name: Build Resume

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Resume Generator
        run: |
          python resumeai.py || echo "No resume generated"

      - name: Upload Resume
        uses: actions/upload-artifact@v4
        with:
          name: generated-resume
          path: ./output/*.pdf

